-- Scalable customer lookup foundation for name and phone search.
-- Address is retained for display only and deliberately has no search index.

create extension if not exists pg_trgm with schema extensions;

alter table public.customers
  add column if not exists id bigint generated by default as identity,
  add column if not exists address text,
  add column if not exists normalized_name text generated always as (
    lower(regexp_replace(btrim(name), '\s+', ' ', 'g'))
  ) stored,
  add column if not exists normalized_phone text generated always as (
    regexp_replace(coalesce(phone, ''), '[^0-9]+', '', 'g')
  ) stored;

-- Preserve the legacy JSON address data while moving reads to a normal text column.
update public.customers
set address = case
  when json_typeof("Customer Adress") = 'string' then "Customer Adress" #>> '{}'
  when "Customer Adress" is not null then "Customer Adress"::text
  else null
end
where address is null;

alter table public.customers
  alter column email drop not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.customers'::regclass
      and contype = 'p'
  ) then
    alter table public.customers add constraint customers_pkey primary key (id);
  end if;
end
$$;

create index if not exists customers_normalized_phone_idx
  on public.customers (normalized_phone text_pattern_ops);

create index if not exists customers_normalized_name_trgm_idx
  on public.customers using gin (normalized_name extensions.gin_trgm_ops);

alter table public.customers enable row level security;

-- The browser never queries this PII table directly. Authenticated requests go
-- through the FastAPI service, which validates the Supabase session and role.
revoke all on table public.customers from anon, authenticated;
revoke all on sequence public.customers_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.customers to service_role;
grant usage, select on sequence public.customers_id_seq to service_role;

analyze public.customers;
