create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  channel text not null check (channel in ('sms', 'whatsapp', 'email')),
  audience text not null check (char_length(audience) between 1 and 120),
  message text not null check (char_length(message) between 1 and 2000),
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'sending', 'sent', 'cancelled')),
  scheduled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists campaigns_user_created_idx on public.campaigns (user_id, created_at desc);
alter table public.campaigns enable row level security;

drop policy if exists campaigns_owner_select on public.campaigns;
create policy campaigns_owner_select on public.campaigns for select using (auth.uid() = user_id);
drop policy if exists campaigns_owner_insert on public.campaigns;
create policy campaigns_owner_insert on public.campaigns for insert with check (auth.uid() = user_id);
drop policy if exists campaigns_owner_update on public.campaigns;
create policy campaigns_owner_update on public.campaigns for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists campaigns_owner_delete on public.campaigns;
create policy campaigns_owner_delete on public.campaigns for delete using (auth.uid() = user_id);